var hair_Options = [
    { "hair_Text" : "심부름꾼", "hair_Value" : "N1" },
    { "hair_Text" : "청부업자", "hair_Value" : "N2" },
    { "hair_Text" : "해결사", "hair_Value" : "N3" },
    { "hair_Text" : "검은손", "hair_Value" : "N4" },
    { "hair_Text" : "암흑의 광휘", "hair_Value" : "R1" },
    //{ "hair_Text" : "사이버네틱", "hair_Value" : "NULL" },
    { "hair_Text" : "지고의 날개", "hair_Value" : "R3" },
    { "hair_Text" : "칠흑의 날개", "hair_Value" : "R4" },
    { "hair_Text" : "드래고니안", "hair_Value" : "R5" },
    { "hair_Text" : "샤이닝스타", "hair_Value" : "U1" },
    { "hair_Text" : "솔로몬의 예복", "hair_Value" : "U2" },
    { "hair_Text" : "하우스키퍼 [A타입]", "hair_Value" : "HOUSE_KEEPER_A" },
    { "hair_Text" : "하우스키퍼 [B타입]", "hair_Value" : "HOUSE_KEEPER_B" },
    { "hair_Text" : "하우스키퍼 [C타입]", "hair_Value" : "HOUSE_KEEPER_C" },
    { "hair_Text" : "하우스키퍼 [D타입]", "hair_Value" : "HOUSE_KEEPER_D" },
    { "hair_Text" : "병아리반", "hair_Value" : "CLOTH_23" },
    { "hair_Text" : "4월의 고양이 헤어", "hair_Value" : "CLOTH_25" },
]