var hand_Options = [
    { "hand_Text" : "심부름꾼", "hand_Value" : "N1" },
    { "hand_Text" : "청부업자", "hand_Value" : "N2" },
    { "hand_Text" : "해결사", "hand_Value" : "N3" },
    { "hand_Text" : "검은손", "hand_Value" : "N4" },
    { "hand_Text" : "암흑의 광휘", "hand_Value" : "R1" },
    //{ "hand_Text" : "사이버네틱", "hand_Value" : "NULL" },
    { "hand_Text" : "지고의 날개", "hand_Value" : "R3" },
    { "hand_Text" : "칠흑의 날개", "hand_Value" : "R4" },
    { "hand_Text" : "드래고니안", "hand_Value" : "R5" },
    { "hand_Text" : "샤이닝스타", "hand_Value" : "U1" },
    { "hand_Text" : "솔로몬의 예복", "hand_Value" : "U2" },
    { "hand_Text" : "하우스키퍼 [A타입]", "hand_Value" : "HOUSE_KEEPER_A" },
    { "hand_Text" : "하우스키퍼 [B타입]", "hand_Value" : "HOUSE_KEEPER_B" },
    { "hand_Text" : "하우스키퍼 [C타입]", "hand_Value" : "HOUSE_KEEPER_C" },
    { "hand_Text" : "하우스키퍼 [D타입]", "hand_Value" : "HOUSE_KEEPER_D" },
    { "hand_Text" : "바니걸 [A타입]", "hand_Value" : "BUNNYGIRL_A" },
    { "hand_Text" : "바니걸 [B타입]", "hand_Value" : "BUNNYGIRL_B" },
    { "hand_Text" : "바니걸 [C타입]", "hand_Value" : "BUNNYGIRL_C" },
    { "hand_Text" : "바니걸 [D타입]", "hand_Value" : "BUNNYGIRL_D" },
]
  
