var lowBody_Options = [
    { "lowBody_Text" : "심부름꾼", "lowBody_Value" : "N1" },
    { "lowBody_Text" : "청부업자", "lowBody_Value" : "N2" },
    { "lowBody_Text" : "해결사", "lowBody_Value" : "N3" },
    { "lowBody_Text" : "검은손", "lowBody_Value" : "N4" },
    { "lowBody_Text" : "암흑의 광휘", "lowBody_Value" : "R1" },
    //{ "lowBody_Text" : "사이버네틱", "lowBody_Value" : "NULL" },
    { "lowBody_Text" : "지고의 날개", "lowBody_Value" : "R3" },
    { "lowBody_Text" : "칠흑의 날개", "lowBody_Value" : "R4" },
    { "lowBody_Text" : "드래고니안", "lowBody_Value" : "R5" },
    { "lowBody_Text" : "샤이닝스타", "lowBody_Value" : "U1" },
    { "lowBody_Text" : "솔로몬의 예복", "lowBody_Value" : "U2" },
    { "lowBody_Text" : "하우스키퍼 [A타입]", "lowBody_Value" : "HOUSE_KEEPER_A" },
    { "lowBody_Text" : "하우스키퍼 [B타입]", "lowBody_Value" : "HOUSE_KEEPER_B" },
    { "lowBody_Text" : "하우스키퍼 [C타입]", "lowBody_Value" : "HOUSE_KEEPER_C" },
    { "lowBody_Text" : "하우스키퍼 [D타입]", "lowBody_Value" : "HOUSE_KEEPER_D" },
    { "lowBody_Text" : "바니걸 [A타입]", "lowBody_Value" : "BUNNYGIRL_A" },
    { "lowBody_Text" : "바니걸 [B타입]", "lowBody_Value" : "BUNNYGIRL_B" },
    { "lowBody_Text" : "바니걸 [C타입]", "lowBody_Value" : "BUNNYGIRL_C" },
    { "lowBody_Text" : "바니걸 [D타입]", "lowBody_Value" : "BUNNYGIRL_D" },
    { "lowBody_Text" : "병아리반", "lowBody_Value" : "CLOTH_23" },
    { "lowBody_Text" : "4월의 고양이 리본 쇼츠", "lowBody_Value" : "CLOTH_25" },
    { "lowBody_Text" : "유니온 아카데미 레이스 스커트 [A타입]", "lowBody_Value" : "CLOTH_26_A" },
    { "lowBody_Text" : "유니온 아카데미 레이스 스커트 [B타입]", "lowBody_Value" : "CLOTH_26_B" },
    { "lowBody_Text" : "유니온 아카데미 레이스 스커트 [C타입]", "lowBody_Value" : "CLOTH_26_A" },
]
  